name: UI Workflow

on:
  push:
    paths:
      - "src/app-ui/**"
      - "test/test-ui/**"
      - ".github/workflows/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

  install:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install source dependencies
        working-directory: ${{ github.workspace }}/src/app-ui
        run: npm install

      - name: Install test dependencies
        working-directory: ${{ github.workspace }}/test/test-ui
        run: npm install

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run source ESLint
        working-directory: ${{ github.workspace }}/src/app-ui
        run: npm run lint:check

      - name: Run test ESLint
        working-directory: ${{ github.workspace }}/test/test-ui
        run: npm run lint:check

  format:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check source formatting with Prettier
        working-directory: ${{ github.workspace }}/src/app-ui
        run: npm run format:check

      - name: Check test formatting with Prettier
        working-directory: ${{ github.workspace }}/test/test-ui
        run: npm run format:check

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Run Jest tests
        working-directory: ${{ github.workspace }}/src/app-ui
        run: npm test
